== Community

=== Website

The website contains the latest information about the project and links
to important information.

The website is located at http://www.ironjacamar.org/

[[userforum]]
=== User forum

The user forum is where we discuss matters about the usage of the
IronJacamar project.

Our forum is located at http://community.jboss.org/en/ironjacamar

[[developerforum]]
=== Developer forum

The developer forum is where we discuss the implementation of the
IronJacamar project. This means the internals of the project and not how
the project is used.

User questions doesn't belong here - they should go in the user forum
instead.

The forum is located at http://community.jboss.org/en/ironjacamar/dev

[[issuetracking]]
=== Issue tracking

We are using JIRA to manage our issues in the project.

These are divided into the following categories

* Feature Request: A feature that you would like see implemented.
* Bug: A software defect.

For all of these you should post your request to our user forum first.

The rest of the categories are for team use only.

Our issue tracking system located at
http://issues.jboss.org/browse/JBJCA
