== Embedded

[[embedded_overview]]
=== Overview

The IronJacamar embedded configuration provides a way of running a JCA
container in-VM.

The configuration is useful when you want a

* JCA container within your environment
* JCA container when doing unit testing

Especially the ability to unit test your resource adapter archives
before deploying them into a testing or a production environment will
benefit developers.

In order to enhance the experience with working with the embedded
configuration the container integrates with the
http://www.jboss.org/shrinkwrap[ShrinkWrap] and
http://arquillian.org/[Arquillian] frameworks.

[[embedded_configuration]]
=== Configuration

You will need all the JAR files located in the

....
$IRON_JACAMAR_HOME/bin
$IRON_JACAMAR_HOME/lib
$IRON_JACAMAR_HOME/lib/embedded
      
....

directories on your application class loader - f.ex.

....
java -classpath allthejarfiles.jar yourapp
      
....

in order to use the embedded configuration.

If you want integration with the Arquillian framework you need to add
the JAR files located in the

....
$IRON_JACAMAR_HOME/lib/embedded/arquillian
      
....

directory as well.

The Arquillian/Byteman integration is located in the

....
$IRON_JACAMAR_HOME/lib/embedded/arquillian/byteman
      
....

directory.

Furthermore you will need to configure Java Naming and Directory
Interface (JNDI) and logging using for example property files.

Sample `jndi.properties` file:

....
java.naming.factory.initial=org.jnp.interfaces.LocalOnlyContextFactory
java.naming.factory.url.pkgs=org.jboss.naming:org.jnp.interfaces
      
....

Sample `logging.properties` file:

....
# Additional logger names to configure (root logger is always configured)
loggers=org.jboss.jca,org.jboss,org.jnp,com.arjuna

# Root logger level
logger.level=${iron.jacamar.log.level:INFO}
logger.handlers=CONSOLE, FILE

# org.jboss.jca
logger.org.jboss.jca.level=DEBUG

# org.jboss
logger.org.jboss.level=INFO

# org.jnp
logger.org.jnp.level=INFO

# com.arjuna
logger.com.arjuna.level=INFO

# Console handler configuration
handler.CONSOLE=org.jboss.logmanager.handlers.ConsoleHandler
handler.CONSOLE.properties=autoFlush
handler.CONSOLE.level=${iron.jacamar.log.console.level:INFO}
handler.CONSOLE.autoFlush=true
handler.CONSOLE.formatter=PATTERN

# File handler configuration
handler.FILE=org.jboss.logmanager.handlers.FileHandler
handler.FILE.level=${iron.jacamar.log.file.level:DEBUG}
handler.FILE.properties=autoFlush,fileName
handler.FILE.autoFlush=true
handler.FILE.fileName=${test.dir}/embedded/test.log
handler.FILE.formatter=PATTERN

# Formatter pattern configuration
formatter.PATTERN=org.jboss.logmanager.formatters.PatternFormatter
formatter.PATTERN.properties=pattern
formatter.PATTERN.pattern=%d{HH:mm:ss,SSS} %-5p [%c{1}] %m%n
      
....

These files needs to be available to the application classloader.

[IMPORTANT]
====
The IronJacamar code generator will generate a test suite based on the
Arquillian functionality, so that setup can be used as a starting point
for your own integration.

The setup will also show you how to use dependencies from the JBoss
Nexus Maven repository instead if you choose the Maven or Ant{plus}Ivy
based build environment.
====

[NOTE]
====
Note that, if you want to be able to deploy datasources you will need to
deploy the

jdbc-local.rar

for

++<++datasource++>++

support, or

jdbc-xa.rar

for

++<++xa-datasource++>++

support. Both archives can be found in the

system/

directory.
====

[[embedded_usage]]
=== Usage

IronJacamar Embedded supports both a simple and an advanced usage model,
using pre-assembled resource adapter archives (.rar) or dynamic resource
adapter archives based on ShrinkWrap.

The embedded environment supports registering resource adapters and
datasources in the platform `MBeanServer` by setting the system property
`ironjacamar.embedded.management` to `true` before starting the
environment.

[[embedded_usage_simple]]
==== Simple usage

The IronJacamar Embedded container environment supports the following
open source testing projects:

[arabic]
. Arquillian
. ShrinkWrap

These extensions allow the developer to use the embedded platform with
greater ease as there doesn't have to be a physical representation of
the resource adapter archive located to the disk.

The Arquillian integration furthermore allows the developer to leave all
the embedded container setup to the integration layer instead.

See the http://arquillian.org/[Arquillian] and
http://www.jboss.org/shrinkwrap[ShrinkWrap] web sites for a detailed
description of the projects and additional documentation.

[[embedded_usage_simple_arquillian_shrinkwrap]]
===== Arquillian and ShrinkWrap

The code sample below shows an usage of deploying a ShrinkWrap resource
adapter archive into the IronJacamar Embedded environment using
Arquillian.

[source,java]
----
          
----

The class makes use of the
`org.jboss.jca.embedded.arquillian.Configuration` annotation in order to
specify that the deployed archive should be auto activated through the
`RAActivator` bean.

[NOTE]
====
Note that, the name for the

ResourceAdapterArchive

must end with the

.rar

extension.
====

[[embedded_usage_simple_arquillian_shrinkwrap_descriptors]]
===== Arquillian and ShrinkWrap/Descriptors

The code sample below shows how to use Arquillian to deploy a ShrinkWrap
resource adapter archive and activate the resource adapter using the
ShrinkWrap/Descriptors API.

This example uses the `org.jboss.jca.embedded.arquillian.Configuration`
annotation to explicit say not to auto activate the resource adapter
archive.

[source,java]
----
          
----

[[embedded_usage_simple_arquillian_byteman]]
===== Arquillian and Byteman

The code sample below shows how to use Arquillian to deploy a ShrinkWrap
resource adapter archive and change the `allocateConnection` of
`org.jboss.jca.core.connectionmanager.AbstractConnectionManager` to
throw a `ResourceException` when the method is called.

The framework used to provide this functionality is called Byteman,
which allows developers to change behavior of a method to for example
throw an exception. This is called fault injection and can be used to
increase code coverage of your project.

[source,java]
----
          
----

See the http://www.jboss.org/byteman[Byteman] web site for a detailed
description of the project and additional documentation.

[[embedded_usage_simple_arquillian_resource]]
===== Arquillian and @ArquillianResource

The Arquillian integration allows the internally used
`org.jboss.jca.embedded.Embedded` or `javax.naming.Context` instances to
be injected into the test case using

[source,java]
----
import org.jboss.jca.embedded.Embedded;
import javax.naming.Context;
import org.jboss.arquillian.test.api.ArquillianResource;

@RunWith(Arquillian.class)
public class ResourceProviderTestCase
{
   @ArquillianResource
   private Embedded embedded;

   @ArquillianResource
   private Context context;

          
----

This will allow direct access to the APIs inside the test case.

[[embedded_usage_simple_ironjacamar]]
===== IronJacamar integration

The code sample below shows how to use Arquillian to deploy a ShrinkWrap
resource adapter archive and inject the IronJacamar metadata repository
into the test case such that assertions can be made.

The IronJacamar container features various components that makes up the
entire Java EE Connector Architecture container. The available list of
components can be viewed in the configuration of the container or
through the management console under the `Kernel` category.

[source,java]
----
          
----

[[embedded_usage_advanced]]
==== Advanced usage

[[embedded_usage_advanced_shrinkwrap]]
===== ShrinkWrap

The code sample below shows an advanced usage of deploying a ShrinkWrap
resource adapter archive into the IronJacamar Embedded environment.

[source,java]
----
          
----

[NOTE]
====
Note that, the name for the

ResourceAdapterArchive

must end with the

.rar

extension.
====

[[embedded_usage_advanced_embedded]]
===== Embedded

The code sample below shows a simple usage of deploying a pre-assembled
resource adapter archive into the IronJacamar Embedded environment.

[source,java]
----
import org.jboss.jca.embedded.Embedded;
import org.jboss.jca.embedded.EmbeddedFactory;

import java.net.URL;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

public class MyTestCase
{
   /** Embedded */
   private static Embedded embedded;

   /** JNDI prefix */
   private static final String JNDI_PREFIX = "java:/eis/";

   /**
    * Simple test to verify deployment of myresourceadapter.rar
    * @throws Throwable throwable exception 
    */
   @Test
   public void testDeployment() throws Throwable
   {
      URL archive = MyTestCase.class.getResource("myresourceadapter.rar");
      Context context = null;
 
      try
      {
         embedded.deploy(archive);

         context = new InitialContext();
         Object o = context.lookup(JNDI_PREFIX + "myresourceadapter");
         assertNotNull(o);
      }
      catch (Throwable t)
      {
         fail(t.getMessage());
      }
      finally
      {
         embedded.undeploy(archive);

         if (context != null)
         {
            try
            {
               context.close();
            }
            catch (NamingException ne)
            {
               // Ignore
            }
         }
      }
   }

   @BeforeClass
   public static void beforeClass() throws Throwable
   {
      // Create an embedded JCA instance
      embedded = EmbeddedFactory.create();

      // Startup
      embedded.startup();
   }

   @AfterClass
   public static void afterClass() throws Throwable
   {
      // Shutdown
      embedded.shutdown();
   }
}
            
----

[NOTE]
====
Note that, the url for the archive must end with the

.rar

extension - either representing a file or a directory.
====

See the IronJacamar Embedded API documentation for additional
functionality.

[[embedded_usage_automaticactivation]]
===== Automatic activation of archives

IronJacamar features a bean called `RAActivator` which will automatic
create a JNDI binding for connection factories and administration
objects. However, sometimes it is of benefit to define these bindings in
a `-ra.xml` file, and therefore `RAActivator` has to be disabled during
that deployment phase.

This done by using the following code snippet

[source,java]
----
import org.jboss.jca.deployers.fungal.RAActivator;

// Disable RAActivator
RAActivator raa = embedded.lookup("RAActivator", RAActivator.class);

if (raa == null)
   throw new IllegalStateException("RAActivator not defined");

raa.setEnabled(false);

embedded.deploy("myrar.rar");
embedded.deploy("myrar-ra.xml");

raa.setEnabled(true);
          
----

which disables the bean, does the deployments and then reenables the
bean again.
